OLED_ENABLE = yes
OLED_DRIVER = SSD1306

ENCODER_ENABLE = no

EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no
MOUSEKEY_ENABLE = yes

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

UNICODEMAP_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Mouse
MOUSEKEY_ENABLE = yes

# Space cadet
SPACE_CADET_ENABLE = yes
COMMAND_ENABLE = no

#Autoshift
AUTO_SHIFT_ENABLE = no

#HID/Virtual Serial
CONSOLE_ENABLE = yes
RAW_ENABLE = yes
VIRTSER_ENABLE = no

#Extras
SRC += features/layer_lock.c
SRC += features/select_word.c
