# Bootloader selection
BOOTLOADER = caterina

OLED_ENABLE = no
OLED_DRIVER_ENABLE = no
ENCODER_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
MOUSEKEY_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
HAPTIC_ENABLE = no
RGB_MATRIX_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
AUTO_SHIFT_ENABLE = no

EXTRAKEY_ENABLE = yes # Audio control and System control
UNICODEMAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
SPACE_CADET_ENABLE = yes
OS_DETECTION_ENABLE = yes

#HID/Virtual Serial
CONSOLE_ENABLE = no
RAW_ENABLE = no
VIRTSER_ENABLE = no

#Extras
SRC += features/layer_lock.c
